/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.darbots.virtualrobotlib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
